### ISSUE TITLE
Latest align2rawsignal executable?

### ISSUE THREAD

**Issue by makostadima** [akundaje/align2rawsignal#2]
Hello Anshul,

Quick question where should I download the latest align2rawsignal executable from?

I found one version here: https://code.google.com/archive/p/align2rawsignal/downloads
and one here: https://personal.broadinstitute.org/anshul/softwareRepo/align2rawsignal_revised.tar.gz

The latter one looks more recent.

Thanks,
Myrto

**Comment by akundaje** [comment]
Use https://code.google.com/archive/p/align2rawsignal/downloads

**Comment by makostadima** [comment]
Will do. Thanks!
